#!/usr/bin/env bash
# Performing a 301 moved permently redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello Worlds!" > /var/www/html/index.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\github.com\/abdulnasirym permanent;"

sudo sed -i "s/server_name _/$new_string" /etc/nginx/sites-enabled/default

sudo service nginx restart

sudo service nginx start
