#!/usr/bin/env bash
# Performing a 301 moved permently redirection

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"

echo "Hello Worlds!" > /var/www/html/index.html

sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.github.com/abdulnasirym/ permanent;" /etc/nginx/sites-available/drfault

sudo service nginx restart
