#!/usr/bin/env bash
# Customizing a 404 error page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

string="server_name _\n\trewrite ^\/redirect_me https:\/\/github.com\/abdulnasirym permanent;"

sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

string_new="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_new/" /etc/nginx/site-enabled/default

sudo service nginx restart

sudo servie nginx start
