#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  abdulnasir-frontend
        bind *:80
        mode http
        default_backend abdulnasir-backend
backend abdulnasir-backend
        balance roundrobin
        server 463453-web-01 100.25.19.204:80 check
        server 463453-web-02 54.210.195.133:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enabling haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart Haproxy
sudo service haproxy restart
