#!/usr/bin/env bash
# Automatatically checks if port 80 is listening else it configure it to listen on port 80

# Ensuring NGINX is installed
sudo systemctl status nginx > /dev/null 2>&1

# Capture the exit status
status=$?

# Evaluate the exit status
if [ $status -eq 0 ]; then
        echo "Nginx is running"
elif [ $status -eq 3 ]; then
        echo "Nginx is not running"
        echo "starting Nginx"
        sudo systemctl start nginx
elif [ $status -eq 4 ]; then
        echo "Nginx service not found"
        echo "Installing Nginx service..."
        sudo apt-get -y update
        sudo apt-get -y install nginx
        sudo systemctl enable nginx
        sudo ufw allow "Nginx HTTP"
        sudo systemctl restart nginx
else
        echo "Unknown status code: $status"
fi

# Checks if netstat tool is installed
if command -v netstat > /dev/null 2>&1; then
        echo "Netstat already installed"
else
        echo "Installing Netsat tools..."
        sudo apt-get -y update
        sudo apt-get -y install net-tools
        echo "Netstat successfully installed"
fi

# Checks if Nginx is listeing on port 80
if ! sudo netstat -tuln | grep -q :80; then
        echo "Configuring Nginx to listen on port 80..."

        # Modifying the default server block to listen on port 80
        sudo sed -i "s/listen 80 default_server;/listen 80;/g" /etc/nginx/sites-enabled/default

        # Ensure firewall allows traffic on port 80
        sudo ufw allow 80/tcp

        # Verify if Nginx is now listening on port 80
        if sudo netsat -tuln | grep -q :80; then
                echo "Nginx is now listening on port 80."
        else
                echo "Failed to configure Nginx to listen on port 80"
        fi
else
        echo "Nginx is already listening on port 80"
fi

